import type { Metadata } from "next";
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8">
          {children}
          </main>
          <Footer />
          </div>
          </body>
    </html>
  );
}
